import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1250px] mx-auto`}
            >
                <header className="px-8 h-[80px] flex justify-end items-center w-full">
                    <nav className="flex gap-10 text-sm uppercase">
                        <Link href="/">Home</Link>
                        <Link href="/blog">Blog</Link>
                        <Link href="/projects">Projects</Link>
                        <Link href="/about">About Me</Link>
                        <Link href="/contact">Contact</Link>
                    </nav>
                </header>
                <div className="p-8">{children}</div>
            </body>
        </html>
    );
}
