import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1250px] mx-auto`}
            >
                <header className="px-8 h-[80px] flex justify-between items-center sticky">
                    <Link href="/">
                        <h1 className="text-[28px] font-extrabold uppercase">
                            Jamie Bower Dev
                        </h1>
                    </Link>
                    <nav className="flex gap-8 font-bold">
                        <Link href="/blog">Blog</Link>
                        <Link href="/about">About Me</Link>
                        <Link href="/contact">Contact</Link>
                    </nav>
                </header>
                <div className="px-8 py-10 min-h-[calc(100dvh-80px)]">
                    {children}
                </div>
            </body>
        </html>
    );
}
